name: Run Daily Main.js

on:
  schedule:
    - cron: '0 6 * * *' # Todos los días a las 06:00 UTC (ajusta si necesitas otra hora)
  workflow_dispatch:

jobs:
  run-daily-job:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar aplicación
        run: node src/backend/index.js
